Availity/sdk-js

packages/api-angular/src/index.js
packages/api-angular/src/settings.js
packages/api-angular/src/tests/api.test.js
packages/api-axios/src/files.js
packages/api-axios/src/index.js
packages/api-axios/src/ms.js
packages/api-axios/src/settings.js
packages/api-axios/src/tests/api.test.js
packages/api-core/src/index.js
packages/api-core/src/resources/README.md
packages/api-core/src/resources/settings.js
packages/api-core/src/resources/tests/settings.test.js

add settings api to api-core
add settings and files api to api-axios

Add Settings Api

---

packages/api-core/src/ms.js
packages/api-core/src/resources/README.md
packages/api-core/src/resources/files.js
packages/api-core/src/resources/tests/files.test.js
packages/upload-core/upload.js

- updated ms.js to check for the error (data not returned in the same format as avApi)
- resumable uploads check more headers to handle and pass errors

add error handling to uploads

---

packages/api-core/src/resources/spaces.js
packages/api-core/src/resources/tests/spaces.test.js

https://github.com/Availity/sdk-js/issues/3

fix(api-core): avSpaces - throw error when no spaceId given

---

packages/api-axios/src/disclaimers.js
packages/api-axios/src/index.js
packages/api-axios/src/tests/api.test.js
packages/api-core/src/index.js
packages/api-core/src/resources/disclaimers.js
packages/api-core/src/resources/tests/disclaimers.test.js

Adds disclaimers endpoint to sdk.

feat(api-core): added new resource for disclaimers

---

packages/api-core/src/resources/slotmachine.js

feat(api-core): add ability to send in variables in AvSlotMachine.query

---

README.md
jest.config.js
package.json
packages/api-axios/package.json
packages/api-core/package.json
packages/api-core/src/api.js
packages/api-core/src/resources/slotmachine.js
packages/api-core/src/tests/api.test.js
packages/authorizations-angular/package.json
packages/authorizations-axios/package.json
packages/authorizations-core/package.json
packages/dl-axios/package.json
packages/exceptions-core/src/tests/test.js
packages/keyv-local-sync/README.md
packages/message-core/src/AvMessage.js
packages/resolve-url/README.md
packages/resolve-url/package.json
packages/resolve-url/resolve-url.js
packages/resolve-url/resolve-url.test.js
packages/upload-core/package.json
packages/upload-core/src/tests/upload.test.js
packages/upload-core/src/upload.js
plop-templates/library/README.md.hbs
plop-templates/library/main.test.js.hbs
plop-templates/library/package.json.hbs
plopfile.js

- fix(upload-core): use full url for tus client
- feat(resolve-url): resolve relative urls to full location href
- chore: add plop template for scaffolding packages
- chore(dl-axios): add axios 0.18 to peerDep
- chore(api-axios): add axios 0.18 to peerDep
- test(exceptions-core): mock stacktrace.js to prevent stacktrace-gps from making actual http connection
@christieb7007 can you review https://github.com/Availity/sdk-js/compare/fix/relative-url?expand=1#diff-84b2e3252d26390567fc675734618604R178 and let me know if you think that refactor would be an issue?

fix: relative urls

---

README.md
plop-templates/resource/test-api-angular.hbs
plopfile.js

Fully automates the creation of api resources by leveraging the "append"
action type from plop.
To test out this PR... check out the README under "Adding a new API Resource" 🚀

chore: automate api resource creation

---

package.json
packages/upload-core/src/tests/upload.test.js
packages/upload-core/src/upload.js

This updates the unit test to test some of the http interactions for upload. The code was also refactored to support testing.

refactor(upload-core): clean up code

---

packages/docs/source/features/yup.md
packages/yup/index.js
packages/yup/src/phone.js
packages/yup/tests/phone.test.js

Porting over the phone validation used in availity-reactstrap-validation.

feat(yup): add phone validation schema

---

package.json
packages/api-core/package.json
packages/api-core/src/api.js
packages/api-core/src/tests/api.test.js
packages/authorizations-axios/package.json
packages/localstorage-core/README.md
packages/localstorage-core/package.json
packages/localstorage-core/src/index.js
packages/localstorage-core/src/tests/test.js
packages/localstorage-core/types/index.d.ts
packages/resolve-url/is-absolute-url.d.ts
packages/resolve-url/package.json
packages/resolve-url/relative-to-absolute.d.ts
packages/resolve-url/resolve-url.d.ts
yarn.lock

- `resolve-url` - adds type defs
- `localstorage-core` - refactored to function and added ts defs

refactoredTypes/ resolve-url & localstorage-core

---

packages/env-var/index.d.ts
packages/env-var/package.json

Adds typescript definition for `@availity/env-var`

refactor(env-var): added ts def

---

packages/message-core/package.json
packages/message-core/types/AvMessage.d.ts
packages/message-core/types/index.d.ts

Adds typescript definitions for `avMessage`.

refactor(message-core): added ts defs

---

packages/native-form/index.d.ts
packages/native-form/package.json

- Adds Typescript Definitions for `@availity/native-form`

refactor(native-form): added ts defs

---

packages/api-core/src/api.js
packages/api-core/src/flattenObject.js
packages/api-core/src/resources/logs.js
packages/api-core/src/resources/tests/logs.test.js
packages/api-core/src/tests/api.test.js

Opening as draft as there are accompanying backend changes for this PR that have not been released
closes #60

feat(api-core): add beacon support to log messages

---

packages/analytics-core/src/analytics.js

Resolves #245 adding dynamic keywords and event modifiers

feat(analytics-core): adding dynamic event modifiers

---

docs/source/features/env-var.md
packages/env-var/src/index.js
packages/env-var/tests/env.test.js

feat(env-var): add env support for cloud urls

---

packages/env-var/src/index.js
packages/env-var/tests/env.test.js

In addition to the prod and non-prod zones, we support an addition "sandbox" zone. This PR adds support for environment detection for sandbox URLs.

feat(env-var): add sandbox support to cloud environment

---

packages/yup/package.json
packages/yup/src/dateRange.js

chore: bump lodash for yup

---

packages/api-axios/package.json
packages/authorizations-axios/package.json
packages/dl-axios/package.json

chore: bump axios

---

packages/api-core/src/api.js

Recent change is appending a list of the next page as the next item, instead of spreading the list

fix(api-core): all should append individual items

---

packages/yup/src/date.js
packages/yup/tests/date.test.js

moment docs:
https://momentjscom.readthedocs.io/en/latest/moment/05-query/06-is-between/
"If the inclusivity parameter is not specified, Moment will default to ()."

feat(yup): support inclusivity option

---

packages/api-axios/src/resources/organizations.js

putting this fix in api-axios as well

fix(api-axios): fix organizations resources check in axios

---

packages/dockyard/src/dockyard.js

fix(dockyard): handle undefined required subfields

---

lerna.json

set `verifyAccess` to false for publishing. npm should handle this

build: disable lerna verification for publish

---

packages/analytics-core/src/tests/util.test.js
packages/analytics-core/src/util.js

fix(analytics-core): recursive getComposedPath calls should be spread

---

.github/CONTRIBUTING.md
README.md

docs: update contributing guide

---

docusaurus/docs/api/uploads.md
packages/upload-core/src/upload.js
packages/upload-core/src/upload.test.js

Fixes an infinite loop that could happen if av scan hangs

fix(upload-core): adds max amount of retries to av scan polling

---

docusaurus/docs/resources/analytics.mdx

docs: clarify analytics docs

---

docusaurus/docs/resources/analytics.md

Some quick follow up docs updates for AvAnalytics

docs(analytics-core): more updates to docs for the AvAnalytics class

---

.github/workflows/deploy.yml

Add `--parallel=1` to publish step

build: make publish run in series

---

packages/api-axios/package.json

Add the "browser" field to make sure the right code is pulled in

fix(api-axios): set the browser field

---

packages/analytics-core/package.json
packages/api-core/package.json
packages/authorizations-axios/package.json
packages/authorizations-core/package.json
packages/dl-axios/package.json
packages/dl-core/package.json
packages/dockyard/package.json
packages/env-var/package.json
packages/exceptions-axios/package.json
packages/exceptions-core/package.json
packages/message-core/package.json
packages/native-form/package.json
packages/relay-id/package.json
packages/resolve-url/package.json
packages/upload-core/package.json
packages/yup/package.json

Adds browser field to package.json. Fixes an issue when used by webpack

fix: add browser field for output

---

docusaurus/docs/api/axios-resources.md
docusaurus/docs/recipes/http-request.md

docs(docusaurus): update wording of docs

---

docusaurus/docs/resources/messaging.md

update messaging docs to reflect new `options` param

docs(message-core): update messaging docs to reflect new `options` param

---

packages/api-axios/src/index.js
packages/api-axios/src/resources/telemetry.js
packages/api-axios/src/resources/tests/telemetry.test.js

feat(api-axios): add telemetry resource

---

packages/api-axios/README.md
packages/api-axios/READMEv5.md
packages/api-axios/src/index.js
packages/api-axios/src/resources/README.md
packages/api-axios/src/resources/routeConfigurations.js
packages/api-axios/src/resources/tests/routeConfigurations.test.js

Adding support for the upcoming route configurations API

feat(api-axios): add route configurations api

---

packages/api-axios/README.md
packages/api-axios/READMEv5.md
packages/api-axios/src/resources/README.md

these changes should have been included in #535

docs(api-axios): add telemetry links

---

packages/api-axios/README.md
packages/api-axios/src/index.d.ts
packages/api-axios/src/index.js
packages/api-axios/src/resources/pdfv2.js
packages/api-axios/src/resources/tests/pdfv2.test.js

This PR adds a new resource to api-axios for the Aries 2 pdf service

feat(api-axios): add aries 2 pdf resource

---

packages/api-axios/src/index.d.ts

add types for `AvTelemetryApi` and `avTelemetryApi`

fix(api-axios): add avTelemetryApi types

---

packages/api-axios/src/index.d.ts

fix(api-axios): export telemetry types

---

docusaurus/project.json
package.json
packages/analytics-core/project.json
packages/api-axios/project.json
packages/api-core/project.json
packages/authorizations-axios/project.json
packages/authorizations-core/project.json
packages/dl-axios/project.json
packages/dl-core/project.json
packages/dockyard/project.json
packages/env-var/project.json
packages/exceptions-axios/project.json
packages/exceptions-core/project.json
packages/message-core/project.json
packages/native-form/project.json
packages/relay-id/project.json
packages/resolve-url/project.json
packages/upload-core/project.json
packages/yup/project.json

This should fix the bug that had v1.0.0 published for several packages

chore: remove $ from semver plugin

---

package.json
yarn.lock

build: upgrade eslint-config-availity

---

docusaurus/docs/api/axios-resources.md
docusaurus/docs/api/getting-started.md
docusaurus/docs/recipes/proxy.md

docs: add AvProxyApi customerId

---

packages/api-axios/package.json
packages/authorizations-axios/package.json
packages/dl-axios/package.json
yarn.lock

chore: upgrade axios

---

yarn.lock

chore: only use one version of axios

---

docusaurus/docs/api/definitions/telemetry.md

docs: add payerId and sessionId to telemetry docs

---

packages/api-axios/src/index.d.ts
packages/api-axios/src/resources/telemetry.js
packages/api-axios/src/resources/tests/telemetry.test.js

- Updated the types for AvApi to accept `http`
- Updated types that were interfaces, but should have been classes
- Updated the route for AvTelemetryApi

fix(api-axios): update url for telemetry

---

packages/analytics-core/project.json
packages/authorizations-axios/project.json
packages/authorizations-core/project.json
packages/dl-axios/project.json
packages/dl-core/project.json
packages/dockyard/project.json
packages/env-var/project.json
packages/exceptions-axios/project.json
packages/exceptions-core/project.json
packages/message-core/project.json
packages/native-form/project.json
packages/relay-id/project.json
packages/resolve-url/project.json
packages/upload-core/project.json
packages/yup/project.json

Add `trackDeps` for `nx` config

build: add trackDeps option

---

yarn.lock

chore: ensure ws is up to date

---

yarn.lock

build: upgrade deps associated with vulnerabilities

---

packages/upload-core/src/index.js
packages/upload-core/src/index.test.js

Added parsing a new header for s3 references

fix(upload-core): parse S3-References

---

packages/api-axios/package.json
packages/authorizations-axios/package.json
packages/dl-axios/package.json
packages/exceptions-core/package.json
packages/yup/package.json
yarn.lock

chore: cleanup peerDeps

---

packages/upload-core/src/index.d.ts

enhanced types for upload-core

fix(upload-core): update types

---

yarn.lock

chore: ensure http-proxy-middleware is up to date

---

packages/upload-core/package.json

fix(upload-core): don't bundle tus

---

yarn.lock

chore: ensure cross-spawn is up to date

---

packages/api-axios/src/api.js

fix where length is retrieved from

fix(api-axios): all logic for limit

---

packages/upload-core/src/index.test.ts
packages/upload-core/src/index.ts

Updated types as they were incorrect. Also now pass the last response to `onSuccess`.

fix: update types and pass lastResponse

---

packages/upload-core/src/index.test.ts
packages/upload-core/src/index.ts

feat(upload-core): add onChunkComplete

---

yarn.lock

build: upgrade image-size, estree-util-value-to-estree, and prismjs

---

packages/api-axios/README.md
packages/api-axios/src/index.js
packages/api-axios/src/resources/dma-cloud.js
packages/api-axios/src/resources/tests/dma-cloud.test.js

v3 log api for aws log service

feat: add dma-cloud url api

---

packages/upload-core/src/index.test.ts
packages/upload-core/src/index.ts

feat(upload-core): allow custom headers

---

.github/workflows/deploy.yml

build: deploy job delete existing version-updates pr

---

.github/workflows/deploy.yml
.github/workflows/repo-metrics.yml

Chore/deps GitHub actions
