Availity/sdk-js

packages/upload-core/upload.js
packages/upload-core/upload.test.js

Moved file type check based on extension to the start method so that the user will see the error message on the progress bar as well.

fix(upload-core): move file type check to start

---

packages/api-core/src/api.js
packages/api-core/src/ms.js
packages/api-core/src/options.js
packages/api-core/src/tests/api.test.js

getLocation(), shouldPoll(), and config.pollingMethod added/moved out

feat(api-core): refactor polling for extending AvMicroservice

---

packages/api-angular/src/index.js
packages/api-angular/src/logs.js
packages/api-angular/src/tests/api.test.js
packages/api-axios/src/index.js
packages/api-axios/src/notification.js
packages/api-axios/src/tests/api.test.js
packages/authorizations-axios/src/index.js

https://github.com/Availity/sdk-js/issues/29
BREAKING CHANGE: export naming conventions have been refactored to match for each implementation (angular/axios). Constructors are prefixed with 'Av', implementations are prefixed with 'av', and Apis are postfixed with 'Api'.

chore(api-core): core, angular, axios api naming consistency

---

packages/api-core/package.json
packages/api-core/src/api.js
packages/api-core/src/tests/api.test.js

Currently postGet will *not* send data as `application/x-www-form-urlencoded` nor will it format the data to `application/x-www-form-urlencoded`. Availity's API's require the data to be sent as `application/x-www-form-urlencoded` with the `Content-Type` header as `application/x-www-form-urlencoded`. This change sets the default way `postGet` works to do just that.

fix(api-core): format postGet payload to standard

---

packages/exceptions-angular/package.json
packages/exceptions-core/package.json
packages/exceptions-core/src/index.js
packages/exceptions-core/src/tests/test.js

Also automatically listen to window.onerror to capture global errors

feat(exception-core): use stacktrace-js for better stacktraces

---

package.json
packages/localstorage-core/src/index.js
packages/localstorage-core/src/tests/test.js

Some of the tests are not really possible as you cannot replace nor spy on localStorage so those tests needed to be removed.

test(localstorage-core): implement tests with jsdom's localStorage

---

packages/api-core/package.json
packages/api-core/src/api.js
packages/api-core/src/ms.js
packages/api-core/src/tests/api.test.js
packages/api-core/src/tests/ms.test.js

BREAKING CHANGE: return the error from the async/await call up the chain so it can be caught in a try/catch

fix(api-core): return error from async/await

---

packages/api-core/package.json
packages/api-core/src/api.js
packages/api-core/src/tests/api.test.js

BREAKING CHANGE: The http error is no longer caught by api-core. Also, the error object is no longer manipulated. Developers must handle the http error by catching the error when using async/await or by leveraging the error callback in the promise chain. The callback `afterResponse` is not called when and error is thrown from http call.

fix(api-core): http should throw errors

---

packages/native-form/index.js

Replaced `append` method with native DOM function `appendChild` as the `append` method is not native to IE and Edge Mobile yet.
https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append

fix: append function is not defined for ie and edge mobile

---

packages/api-core/package.json
packages/resolve-url/README.md
packages/resolve-url/is-absolute-url.js
packages/resolve-url/is-absolute-url.test.js
packages/resolve-url/package.json
packages/resolve-url/relative-to-absolute.js
packages/resolve-url/relative-to-absolute.test.js
packages/resolve-url/resolve-url.js
plop-templates/library/package.json.hbs

Unfortunately, the two libs chosen for relative url resolution did not work in IE11 without compilation. 
- https://github.com/rubensworks/relative-to-absolute-iri.js
- https://github.com/sindresorhus/is-absolute-url
Each lib was embedded within `resolve-url`. Future versions of our toolkit should probably compile all of `node_modules` to prevent this from happening again.

fix(resolve-url): make ie11 compat

---

packages/analytics-core/README.md

Clarifies that to create a new `AvSplunkAnalytics`, you need to pass an instance of `AvLogMessages` rather than just the class

docs(analytics-core): clarify first arg to new AvSplunkAnalytics

---

packages/api-core/src/api.js

Enables an AvApi.post call to exit gracefully if one of the subsequent polls is a 405 without a config

fix(api-core): graceful exit when polling

---

packages/analytics-core/src/dma.js
packages/analytics-core/src/tests/dma.test.js

This is being handled on the serverside now.

refactor(analytics-core): removed default tpId to NA when not found

---

README.md
plop-templates/resource/api-angular-resource.js.hbs
plop-templates/resource/api-axios-resource.js.hbs
plop-templates/resource/api-core-ms-resource.js.hbs
plop-templates/resource/api-core-resource.js.hbs
plop-templates/resource/api-core-test.js.hbs
plopfile.js

closes #114
Adds plop generator for adding a new api resource. Also adds a section to
the README that serves as a checklist for the developer creating the
resource and for the reviewer reviewing the PR.

chore: add plop generator for api resources

---

packages/yup/src/dateRange.js

Date range was validating the min and max since they came in as objects sometimes but without a value. Requires the value to be there now or else it won't validate.

fix(yup): fixed bug in daterange causing to validate improperly

---

packages/api-core/src/api.js
packages/api-core/src/tests/api.test.js

Removing response url from relative url calculation.

fix(api-core): do not use config url when resolving location header

---

packages/api-core/src/resources/organizations.js
packages/api-core/src/resources/tests/organizations.test.js

Skips unnecessary call to `avUsers` resource if the `userId` for the call
is already defined in the `params`
closes #147

perf(api-core): use userId from params if it exists in getOrganizations

---

packages/api-core/src/resources/settings.js
packages/api-core/src/resources/tests/settings.test.js

Skips unnecessary call to `avUsers` resource if the `userId` for the call
is already defined in `config.params` (for `getApplication`) or `data.scope` (for `setApplication`)

perf(api-core): use userId if it exists in get,set application settings

---

packages/api-core/src/resources/pdfs.js
packages/api-core/src/resources/tests/pdfs.test.js

`utils/v1/pdfs` (success) response format is:
```json
{
"links" : {
"pdf" : {
"href" : "host/api/utils/v1/pdfs/{id}.pdf"
},
"self" : {
"href" : "hostapi/utils/v1/pdfs/{id}"
}
},
"id" : "4221042154297172908",
"createdDate" : "{timestamp}",
"updatedDate" : "{timestamp}",
"expirationDate" : "{timestamp}",
"status" : "Complete",
"statusCode" : "4",
"applicationId" : "{requestedAppID}",
"fileName" : "{requestedFileName}"
}
```

fix(api-core): Corrected PDF expected response

---

docs/gatsby-config.js
docs/source/features/relay-id.md
packages/relay-id/README.md
packages/relay-id/index.d.ts
packages/relay-id/package.json
packages/relay-id/src/index.js
packages/relay-id/tests/test.js

Title says it all.
Its a subset of `graphql-relay` or `graphql-compose-relay`. Just contains the logic for encoding/decoding.
Example:
```js
import { fromGlobalId, toGlobalId } from '@availity/relay-id';
// Will return {type: 'User', id: '789'}
const { type, id } = fromGlobalId('VXNlcjo3ODk=');
// Will return global id of VXNlcjo3ODk=
const globalId = toGlobalId('User', '789');
```
[Inspired By](https://github.com/graphql-compose/graphql-compose-relay/blob/master/src/globalId.js)

feat(relay-id): new small helper package to help deal with relay ids

---

docs/source/api/uploads.md
packages/upload-core/src/upload.js

Update to increase av scan upload polling time to 5000ms by default, but allow for customization. 
closes #198

feat(upload-core): increase file upload polling time and add config

---

packages/api-core/src/resources/regions.js
packages/api-core/src/resources/tests/regions.test.js

Avoids unnecessary call to `avUsers.me()` if we already have a `userId`.

perf(api-core): use userId if it exists in call to getRegions

---

packages/api-core/src/api.js
packages/api-core/src/resources/logs.js
packages/api-core/src/resources/tests/logs.test.js
packages/api-core/src/tests/api.test.js

Modifies the `content-type` from `multipart/form-data` to `url-encoded` so that it plays nicely with our A1 and A2 APIs.

refactor(api-core): updated send beacon to send as encoded form data

---

docs/source/api/getting-started.md

Forgot to update docs when working on patch(). This PR updates docs for api-core to include the new method.

docs(api-core): Updated docs to reflect new patch method

---

packages/analytics-core/src/analytics.js

On first DOM load, the `url` object is `undefined` so we default to the `window.location.href`. However on subsequent hash changes its an object with the `newURL` as a property so we need to strip it for the proper new url to post.

refactor(analytics-core): fixed issue with hashchange

---

packages/api-core/src/resources/README.md
packages/api-core/src/resources/organizations.js
packages/api-core/src/resources/tests/organizations.test.js

Update getFilteredOrganizations to use AND/OR permission/resource logic

feat(api-core): add permission AND/OR logic to organization filter

---

packages/api-core/src/api.js
packages/api-core/src/ms.js
packages/api-core/src/options.js
packages/api-core/src/resolve-host.js
packages/api-core/src/tests/api.test.js
packages/api-core/src/tests/ms.test.js

This PR is to handle API calls made with relative URLs when the app has been served from Cloudfront.

feat(api-core): route api calls to on-prem when called from cloud apps

---

packages/api-core/src/resources/organizations.js
packages/api-core/src/resources/tests/organizations.test.js

getFilteredOrganizations will return the UserPermissions list of orgs with the resources attached so they can be used for other permission'd things, such as getting payers.

refactor(api-core): org api filtered call returns org list with resources

---

packages/api-core/src/resources/organizations.js
packages/api-core/src/resources/tests/organizations.test.js

fixes when calling a superset of the previous permissions is returned as equal

fix(api-core): fix filteredOrgs arePermissionsEqual check

---

packages/yup/src/date.js
packages/yup/tests/date.test.js

Discovered an edge case where yup was correctly validating an invalid date format/input (e.g. 01/01/20011), and displaying feedback text, but was *NOT* blocking form submission. Fix made to align behavior with other invalid cases (min/max, required, etc.), and block submission when input is invalid. Also, added tests.

fix(yup): avDate fix for edge case invalid date length

---

packages/yup/src/date.js
packages/yup/tests/date.test.js

This fix removes a `typeError` message on empty date fields, allowing user to enter a date and then remove it without leaving up an error message because the field had been touched.

fix(yup): avDate.typeError should not display for empty fields

---

packages/yup/src/date.js
packages/yup/tests/date.test.js

Allows users to utilize .typeError('someCustomMessage')
If .typeError is not utilized, default error message will be 'Date is invalid.'

fix(yup): refactor typeError, use _typeCheck

---

packages/native-form/index.d.ts
packages/native-form/package.json
packages/native-form/src/index.js
packages/native-form/tests/nativeForm.test.js

BREAKING CHANGE: native-form now exports an async function, no longer defaults type
MIGRATION:
Before: nativeForm(...args);
After: await nativeForm(...args);

feat(native-form): call avWebQLApi to obtain sso type

---

yarn.lock

The current build is having an issue with the lockfile. I ran `yarn clean` to remove `node_modules` and then `yarn install` which generated a new lockfile.

build: run yarn install to update lock file

---

packages/yup/package.json

BREAKING CHANGE: the version of yup this package requires contains breaking changes from 0.32.0 onward
https://github.com/jquense/yup/blob/375f1b9ed41f5043e123ea87a01a2dfe333c3927/CHANGELOG.md#0320-2020-12-03
Major version bump was missed in #392

fix(yup): package change for major version update

---

packages/analytics-core/src/analytics.js
packages/analytics-core/src/tests/analytics.test.js
packages/analytics-core/types/analytics.d.ts

Updated the types for the analytics-core package. Marked `url` is optional for `trackPageView`

fix(analytics-core): update types and error msg

---

packages/api-axios/src/proxy.js
packages/api-axios/src/tests/proxy.test.js

The url was not being created properly. I copied over the logic from api-core, and brought it back into the proxy class

fix(api-axios): url creation was not working as expected

---

packages/message-core/src/AvMessage.d.ts

According to [these docs](https://availity.github.io/sdk-js/resources/messaging), the `subscribe` method on AvMessage class returns an unsubscribe function. But the type definitions had it returning void.
This fixes that return type.

fix(message-core): fix return type for AvMessage.subscribe

---

.lintstagedrc.js
docusaurus/docs/resources/yup.md
docusaurus/package.json
package.json
packages/yup/src/date.ts
packages/yup/src/dateRange.ts
packages/yup/src/tests/date.test.ts
packages/yup/src/tests/dateRange.test.ts
packages/yup/src/tests/npi.test.ts
tsconfig.json

I refactored how the `avDate` and `dateRange` schema work. This fixes errors with chaining the methods. 
I expanded the allowed valid formats. I didn't see why we should arbitrarily limit it as long as `moment` knows how to parse the value properly. 
`avDate` constructor now accepts `typeError` which will set the typeError message. the typeError method from `yup` can still be used as well

feat(yup): update how accepted formats are handled for dates

---

packages/message-core/src/AvMessage.d.ts
packages/message-core/src/AvMessage.js
packages/message-core/src/AvMessage.test.js

Old behavior for AvMessages is that subscription callbacks are not called when a message event is emitted from the same window where the subscription is registered. This PR adds an `options` object as a third parameter to `avMessages.subscribe` where `ignoreSameWindow` can be set to `false`. This option defaults to `true` to match old behavior. 
Example:
```js
import avMessages from '@availity/message-core'
const avMessages = new AvMessages()
const handleEvent = () => { 
// ...do some work
}
avMessage.subscribe('my-test-event-name', , { ignoreSameWindow: false } )
```
The above example will call `handleEvent` regardless of whether `my-test-event-name` is dispatched from the same window or a different window such as a child iframe's window.

feat(message-core): add ignoreSameWindow boolean option

---

packages/api-core/package.json

This will start the publishing of `@availity/api-core` again

build(api-core): add back publishing script

---

.github/workflows/deploy.yml
.github/workflows/pr-build.yml
docusaurus/docs/intro.md
docusaurus/docusaurus.config.js
docusaurus/package.json
yarn.lock

- bumping docusaurus from 2.0 alpha to major release
- algolia now requires appid which we do not have access to. commented out atm.
- requires node 16, updated github actions

feat(docusaurus): upgrade docusaurus to v2

---

packages/api-axios/mocks/handlers.js
packages/api-axios/mocks/server.js
packages/api-axios/package.json
packages/api-axios/src/index.d.ts
packages/api-axios/src/resources/regions.js
packages/api-axios/src/resources/tests/regions.test.js
packages/api-axios/tsconfig.json
yarn.lock

There was a bug where the `afterUpdate` function in `AvRegionsApi` would throw an error because it would lose the context of `this`. I changed the `afterUpdate` to be an arrow function to make sure it inherits `this`. I added a test and `msw` to make sure it is properly tested.

fix(api-axios): make afterUpdate an arrow function

---

packages/api-axios/src/resources/regions.js
packages/api-axios/src/resources/tests/regions.test.js

`AvRegionSelect` will currently use the wrong data from the response if the param `userId` is passed. This change ensures the `regions` array is returned when `all()` is called.

fix(api-axios): override getQueryResultKey for regions

---

packages/env-var/src/index.js

i needed to return undefined and i couldn't so i made this
alternately: we could error locally and warn in non-prod if developer tries to use undefined

feat(env-var): allow users to return undefined

---

packages/dl-axios/src/download.js

Getting the below error when trying to start a react app using axios 1.5.0 and dl-axios 5.0.1
ERROR in ../../node_modules/@availity/dl-axios/dist/index.js 31:27-53
Module not found: Error: Package path ./lib/utils is not exported from package ../node_modules/axios (see exports field in ../node_modules/axios/package.json)
The axios v1 bump from dl-axios v5 did not account for the change in hidden util functions. Although I don't think we have any need to use axios's merge. Updated this resource to be consistent with our other resources

fix(dl-axios): v1.x of axios broke an import, update this class

---

packages/api-axios/src/api.js

This ensures that the pollingMethod specified in the request config is respected.

fix(api-axios): use newConfig.pollingMethod as polling method

---

packages/dl-axios/src/index.js

This export was probably refactored after updating eslint-config-availity caused an error here, but this changed the export from being default to named. Any projects using the old default import would be broken by this change.

fix(dl-axios): revert back to default export to avoid a breaking change

---

packages/api-axios/src/ms.js
packages/api-axios/src/tests/ms.test.js

Allow for absolute urls to be used with AvMicroserviceApi

fix(api-axios): allow absolute urls

---

packages/native-form/src/index.d.ts

Mui spaces-link actually uses the TS checks and native form should accept types besides 'saml' and 'openid' so we can actually use the logic that fetches the saml config by id

fix(native-form): allow any sso type
